### ISSUE TITLE
add perl libraries

### ISSUE THREAD

**Issue by aero** [lqez/awesome-hangul#4]
Encode::Korean - Perl extension for Encodings of Korean Language
https://metacpan.org/pod/Encode::Korean

Lingua::KO::Romanize::Hangul - Romanization of Korean language
https://metacpan.org/pod/Lingua::KO::Romanize::Hangul

**Comment by lqez** [comment]
Thanks. Closed by #3 and 
https://github.com/lqez/awesome-hangul/commit/029b42470a487bdbd5321c1ede010750aad7ca5e
